### ISSUE TITLE
Reaction Failed message not appearing in Normal mode

### ISSUE THREAD

**Issue by KayalvizhiSadayappan** [shiyuning/HBV-BioRT#16] opened 2021-03-02 17:45 UTC
I have attached the screen display for normal mode where you can see no error messages are displayed. When the same simulation is run in verbose mode, reaction fails at all time steps as can be seen in another attached figure. It will be better if you can modify the code such that the reaction failed message appears in normal mode too (like in 'normal mode after modification; image). Hope you understood what I mean. If not, let me know. Thanks! 

P.S: I used the latest version downloaded yesterday
![normal mode](https://user-images.githubusercontent.com/70716152/109691122-1b933180-7b55-11eb-8332-1d121b03cd75.png)
![verbose mode](https://user-images.githubusercontent.com/70716152/109691134-1df58b80-7b55-11eb-9aed-f97f27647fae.png)
![normal mode after modification](https://user-images.githubusercontent.com/70716152/109691141-1fbf4f00-7b55-11eb-9ca5-be8d3fc99922.png)

**Comment by shiyuning** [comment] 2021-03-02 18:00
This is a duplicate of #13

**Closed by shiyuning** 2021-03-02 18:00 UTC
Labels: duplicate
